import type { AppLanguage } from "../state/languageSettings";

const text = {
  en: {
    autosaved: "Autosaved locally",
    exportPng: "Export PNG",
    exportPlan: "Export Plan",
    importPlan: "Import Plan",
    reset: "Reset",
    aboutTitle: "About PlanGrid",
    helpAria: "What is PlanGrid and how is it used?",
    planHealth: "Plan health",
    warnings: "Warnings",
    noWarnings: "No plan warnings.",
    unplaced: "Unplaced",
    storage: "Storage",
    storageEmpty: "Drop unplaced courses here.",
    catalogEyebrow: "Uniandes catalog",
    addCourses: "Add courses",
    source: "Source",
    allSources: "All sources",
    currentApi: "Current API",
    catalogOnly: "Catalog only",
    unverified: "Unverified",
    mutedCatalogOnly: "Muted catalog-only cards",
    courseQuery: "Course code, name, or requirement",
    searchPlaceholder: "ISIS-1225, structures, or EP",
    search: "Search",
    searching: "Searching",
    department: "Department",
    allDepartments: "All departments",
    dragHint: "Drag any result directly into a semester or storage.",
    startingPoints: "Starting points",
    presets: "Presets",
    usePreset: "Use preset",
    academicRoadmap: "Academic roadmap",
    planOptions: "Plan options",
    recognizedRequirements: "Recognized requirements",
    colorOverrides: "Color overrides",
    language: "Language",
    totalPlanCredits: "Total plan credits",
    semesters: "Semesters",
    creditLimit: "Credit limit",
    editFirstPeriod: "Edit first period",
    dropCoursesHere: "Drop courses here",
    disclaimer:
      "Unofficial planning tool. Confirm final plans with academic coordination or an advisor.",
    languagePromptTitle: "Choose your language",
    languagePromptEyebrow: "Welcome",
    languagePromptBody:
      "PlanGrid starts in English. You can switch the interface to Spanish now or change it later from the plan options menu.",
    continueEnglish: "Continue in English",
    switchSpanish: "Usar español",
    close: "Close",
  },
  es: {
    autosaved: "Guardado local",
    exportPng: "Exportar PNG",
    exportPlan: "Exportar plan",
    importPlan: "Importar plan",
    reset: "Reiniciar",
    aboutTitle: "Acerca de PlanGrid",
    helpAria: "¿Qué es PlanGrid y cómo se usa?",
    planHealth: "Estado del plan",
    warnings: "Alertas",
    noWarnings: "No hay alertas del plan.",
    unplaced: "Sin ubicar",
    storage: "Storage",
    storageEmpty: "Suelta cursos sin ubicar aquí.",
    catalogEyebrow: "Catálogo Uniandes",
    addCourses: "Agregar cursos",
    source: "Fuente",
    allSources: "Todas las fuentes",
    currentApi: "API actual",
    catalogOnly: "Solo catálogo",
    unverified: "Sin verificar",
    mutedCatalogOnly: "Atenuar cursos solo catálogo",
    courseQuery: "Código, nombre o requisito",
    searchPlaceholder: "ISIS-1225, estructuras, o EP",
    search: "Buscar",
    searching: "Buscando",
    department: "Departamento",
    allDepartments: "Todos los departamentos",
    dragHint: "Arrastra cualquier resultado a un semestre o a Storage.",
    startingPoints: "Puntos de partida",
    presets: "Plantillas",
    usePreset: "Usar plantilla",
    academicRoadmap: "Ruta académica",
    planOptions: "Opciones del plan",
    recognizedRequirements: "Requisitos reconocidos",
    colorOverrides: "Colores especiales",
    language: "Idioma",
    totalPlanCredits: "Créditos totales",
    semesters: "Semestres",
    creditLimit: "Límite de créditos",
    editFirstPeriod: "Editar primer periodo",
    dropCoursesHere: "Suelta cursos aquí",
    disclaimer:
      "Herramienta no oficial. Confirma el plan final con coordinación académica o consejería.",
    languagePromptTitle: "Elige tu idioma",
    languagePromptEyebrow: "Bienvenida",
    languagePromptBody:
      "PlanGrid inicia en inglés. Puedes cambiar la interfaz a español ahora o hacerlo luego desde las opciones del plan.",
    continueEnglish: "Continuar en inglés",
    switchSpanish: "Usar español",
    close: "Cerrar",
  },
} as const;

export type LanguageTextKey = keyof typeof text.en;

export function getLanguageText(language: AppLanguage, key: LanguageTextKey): string {
  return text[language][key];
}
